title: "Fortgeschrittene Programmierkonzepte (FPK)"
email: korbinian.riedhammer@fh-rosenheim.de
description: "Materialien zum Pflichtmodul Fortgeschrittene Programmierkonzepte"
baseurl: ""
url: "https://hsro-inf-fpk.github.io"
exclude: ["LICENSE", "Remarks.md", "examples"]
github_username: ["sikoried"]

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
